### PR TITLE
Add a way to easily mount your own routes

### PR DESCRIPTION
**Pull request by oliverwoodings**
Working on a personal project, I just want to mount some routes. Don't want to have to reimplement all the server stuff myself. Figured this is a nice solution!

### CODE REVIEW

**Comment by KidkArolis** [comment]
It's definitely the case that jetpack is meant to make both client/server simple to start with. There's already a way to do something similar to what you're suggesting, it just wasn't documented in the readme before, I've just added a paragraph:

https://github.com/KidkArolis/jetpack#jetpackserver

The reason I currently prefer this approach of creating a server.js file instead of adding logic to jetpack config is because it keeps config and code separate, which seems better. And if your app grows, it's less of a jump to swap jetpack/server with a server of your own. (which currently it's quite possible yet, as I haven't implemented `jetpack/handle`).

Let me know what you think.

**Comment by oliverwoodings** [comment]
Oh sweet! Thats awesome :)

**Comment by oliverwoodings** [comment]
Ah, but what about the mode with the webpack dev server? Do you just run it separately?

**Comment by KidkArolis** [comment]
jetpack will run both client via webpack and server via nodemon and proxy
one to the other so their both behind a single port. See the not very clear
(and not very accurate) architecture diagrams in readme.

**Pull request closed without merging**
